### ISSUE TITLE
点击文件上传后，post地址请求了两次

### ISSUE THREAD

**Issue by accpdyk** [lian-yue/vue-upload-component#106]
第一次没有提交文件，第二次有，
代码：
`   
        <ul>
            <li v-for="file in files">{{file.name}} - Error: {{file.error}}, Success: {{file.success}},{{file.active}}</li>
        </ul>

        <file-upload  ref="upload"
                      v-model="files"   @input-file="inputFile"   @input-filter="inputFilter"
                      :extensions="['jpg', 'gif', 'png', 'webp']" accept="image/*"
                      post-action="http://exam.dyk.mschool.cn/operate/card/upload-img?key=54493476-3010-4e7a-a707-69d2f0c23fb2&exam_id=164" :data="{'container_id':'1000'}"
        >
            上传文件
        </file-upload>
        <button @click="$refs.upload.active=true">上传</button>
`

`
methods:{`
      inputFile(newFile,oldFile){

        if (newFile && !oldFile) {
          // add
          console.log('add',newFile);
        }
        if (newFile && oldFile) {
          console.log('update',oldFile)
        }
        if (!newFile && oldFile) {
          // remove
          console.log('remove',oldFile)
        }
      },
      inputFilter: function (newFile, oldFile, prevent) {
        if (newFile && !oldFile) {
          // 过滤不是图片后缀的文件
          if (!/\.(jpeg|jpe|jpg|gif|png|webp)$/i.test(newFile.name)) {
            return prevent()
          }
        }
      }
    },

`

**Comment by lian-yue** [comment]
https://jsbin.com/nekohivaxi/1/edit?html,js,console,output
测试并没多次请求
请分清楚 `OPTIONS`  和`POST` 请求

**Comment by accpdyk** [comment]
对，是OPTIONS请求。

**Comment by jimyuan** [comment]
跨域吗? 有 options 很正常啊，一般都会有啊！
