### ISSUE TITLE
移动端ios测试，好像并不能限制图片格式

### ISSUE THREAD

**Issue by rainwalkerhu** [lian-yue/vue-upload-component#107]
accept: 'image/png,image/jpeg,image/jpeg',extensions: 'jpg,jpeg,png'这个是我的设置，我做的webapp，项目在电脑上打开是可以正确限制图片格式的，但是在手机上（苹果机测试）好像并不能限制选择的图片格式（测试上传web成功），不知什么原因

**Comment by lian-yue** [comment]
`ios`  上的`safari` 也不行？ 苹果几乎只能选择图片吧

**Comment by rainwalkerhu** [comment]
能选择图片，只是不能限制图片格式，比如我设置的webp格式不能选择不能上传，但在ios的webview上还是能够选择并且上传，这个是测试部的同时测试出来的bug，因为这个项目做了登录限制无法在公司开发的原生外壳以外的环境登录所以并不能验证safari是否存在该问题，已经确认的是app用的是系统webview,并没有内置webview

**Comment by rainwalkerhu** [comment]
补充一点，针对“能选择图片，只是不能限制图片格式，比如我设置的webp格式不能选择不能上传，但在ios的webview上还是能够选择并且上传”，这句话做一点补充，就是被限制格式的图片会稳定上传失败，不知道是被extentions取消了还是其他原因

**Comment by lian-yue** [comment]
`accept` 就是 html 的  属性 支持不支持 是看浏览器支持是否
最好的方法是使用 [@input-filter](https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E4%BA%8B%E4%BB%B6-input-filter) 过滤器 过滤掉不是图片的文件 但是还是能选择只不过不会到列表里面了

**Comment by rainwalkerhu** [comment]
嗯嗯，好的，已经在回调里面手动过滤了，谢谢回复
