### ISSUE TITLE
在微信客户端下，设置multiple=true时没有拍照选择按钮

### ISSUE THREAD

**Issue by yangxuilyx** [lian-yue/vue-upload-component#109]
由于需求上需要在微信上上传多个图片，设置后发现multiple=true时不能拍照选择，只能从相册中选择，请问是否可以去掉multiple对文件个数的限制？谢谢

**Comment by lian-yue** [comment]
专门为你添加了一个参数 

https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E5%B1%9E%E6%80%A7-maximum

```html
<file-upload :multiple="false" :maximum="0"></file-upload>
```

**Comment by yangxuilyx** [comment]
可以啦，非常感谢
