### ISSUE TITLE
Drop - canceled by ESC

### ISSUE THREAD

**Issue by vmartis** [lian-yue/vue-upload-component#110]
$refs.upload.dropActive is still 'true' when drop of file is canceled by pressing ESC key.  The problem is in 'onDragLeave' callback.
```
 onDragleave(e) {
      e.preventDefault()
      if (e.target.nodeName === 'HTML' || (e.screenX === 0 && e.screenY === 0 && e.screenY === 0 && !e.fromElement && e.offsetX < 0)) {
        this.dropActive = false
      }
    }
```
When dropping of file is canceled by pressing of ESC key, `e.offsetX` equals `0`. Also `e.screenY === 0` is duplicated in expression. I have created the PR with fix.

**Comment by JoshMoreno** [comment]
@lian-yue Looks like this was resolved. It's working as expected for me.
https://github.com/lian-yue/vue-upload-component/pull/111

Can you close this?
