### ISSUE TITLE
ie11的问题，怎么解决

### ISSUE THREAD

**Issue by haiwei27** [lian-yue/vue-upload-component#112]
![image](https://user-images.githubusercontent.com/14025538/33009110-b3a9544a-ce10-11e7-962b-1a6e7bf21d86.png)

**Comment by haiwei27** [comment]
这个例子运行失败

**Comment by lian-yue** [comment]
https://stackoverflow.com/questions/39266801/saving-file-on-ie11-with-filesaver

`IE 11`  好想 不支持 `new FIle` 改成 `new Blob` 就好了
`Blob` 参数稍微有点不同

**Comment by zhoujingang** [comment]
给力

**Comment by haiwei27** [comment]
解决了，大神真给力啊！谢谢！
