### ISSUE TITLE
Feature - manually set drop zone

### ISSUE THREAD

**Issue by mavrick** [lian-yue/vue-upload-component#115]
Would love an option to manually set the drop zone element instead of the parent element.

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/documents#options-props-drop

You can use the css selector

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/documents#options-props-drop

You can use the css selector

**Comment by mavrick** [comment]
@lian-yue thanks, yup - i totally missed that in the docs. thank you :)

**Comment by stacieweff** [comment]
@mavrick @lian-yue  Can you provide an example of this? Trying to set the drop zone to a specific div within my component, but having issues.
