### ISSUE TITLE
图片压缩找不到ImageCompressor问题

### ISSUE THREAD

**Issue by yangxuilyx** [lian-yue/vue-upload-component#117]
我在示例代码中发现有使用到ImageCompressor压缩图片，我配置autoCompress后，报没有ImageCompressor的错误，请问下您使用的是第三方的图片压缩软件，还是您自己使用的，我在api文档中没有找到。能否告知？谢谢

**Comment by lian-yue** [comment]
第三方。
这个只是上传，并且只是一个按钮
并没压缩功能

**Comment by yangxuilyx** [comment]
能否发下这个插件的地址呢？

**Comment by lian-yue** [comment]
https://github.com/xkeshi/image-compressor
这个， 我记得chrome 有的版本 有bug  好像大于 2m 的会被异常。
建议你找 其它压缩的插件

**Comment by yangxuilyx** [comment]
我主要在微信上使用，先试下吧，谢谢
