### ISSUE TITLE
Can't upload to absolute url

### ISSUE THREAD

**Issue by adnanmokhtar** [lian-yue/vue-upload-component#119]
when ichange post-action to full absolute url line 'http://dreamadmin.n-stream.tv/api/restful/1.0/portal/upload/videos'

it send empty OPTIONS request without the file

![image](https://user-images.githubusercontent.com/21971198/33298207-b41c28fc-d3ed-11e7-89dc-231d65c607ca.png)

please help

**Comment by lian-yue** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by AnkerCheng** [comment]
这是跨域的问题。用nginx把页面和后台API代理一下就行了。
