### ISSUE TITLE
动态改变headers的数据不起作用

### ISSUE THREAD

**Issue by acfasj** [lian-yue/vue-upload-component#127]
用的drag and drop的例子, 方法是post
当我改变prop绑定的headers的数据的时候, 发出的请求并没有看到数据的改变
`<file-upload
        class="btn btn-primary"
        name="files[]"
        post-action="//127.0.0.1:99/api/upload"
        :headers="headers"
        :data="bodyPlayload"
        :multiple="true"
        :drop="true"
        :drop-directory="true"
        v-model="files"
        ref="upload">
      </file-upload>`

比如原先绑定的`headers: { p1: 'value1' }`, 发出的请求带有 p1: value1
然后变为`headers: { p1: 'value1',  p2: 'value2' }`,  发出的请求仍只带有 p1: value1
绑定的data也是一样
求教

**Comment by lian-yue** [comment]
`headers` 改变后新添加的文件才会用新的 `headers`  
如果需要动态请使用 
[`@input-filter`](https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E4%BA%8B%E4%BB%B6-input-filter)  事件


```js
inputFilter(newFile, oldFile, prevent) {
  if (newFile && oldFile) {
    // 激活前
    if (newFile.active !== oldFile.active) {
      newFile.headers = {
        'X-Token': 'value1'
      }
    }
  }
}
```

**Comment by acfasj** [comment]
@lian-yue 原来是这样, 多谢你的解答~
我做的是新建一篇帖子, 帖子有附件, 帖子和附件是一对多关系
我的做法是后台新建一篇帖子成功后返回一个帖子id, 附件的上传需要这个帖子id, id要放到data
这样看来用不了你这个组件了

**Comment by lian-yue** [comment]
我说了   使用过滤器 就可以 了 实时修改 
并不是不能用

**Comment by acfasj** [comment]
@lian-yue 抱歉现在才看到   
我的需求是在一篇帖子点击发布之前  用户就已经把文件都添加好了  然后点击发布  先创建帖子返回帖子id再上传文件  
我的理解是   过滤器事件里可以实时修改headers等数据是在添加文件的时候  所以我认为满足不了我这个逻辑   
文档我也不是看得很明白  当然我没有抬杠的意思  毕竟能有作者那么积极热心的回复已经很感谢了~
