### ISSUE TITLE
withCredentials ？？？？？？？

### ISSUE THREAD

**Issue by evolutionjay** [lian-yue/vue-upload-component#128]
这个怎么设置？ 
我看了有个 issues #85  写了， 但我设置了没用， 文档来一个说明下？

**Comment by evolutionjay** [comment]
看了你的源码，似乎要修改源码了

**Comment by evolutionjay** [comment]
我自己添加了个 Pull requests， 麻烦审核通过一下， 顺便自己build 一下， 你的源码我在本地没办法跑起来， 提示  vue / vue loader 版本不一致， 我懒的去看看匹配的版本。

**Comment by lian-yue** [comment]
https://jsbin.com/ceyohitimi/1/edit?html,js,console,output
支持 设置 withCredentials 又拍云 不支持 cookies 参数 修改成自己的域名测试就可以了

**Comment by evolutionjay** [comment]
@lian-yue   , 在 filter-input 的时候找不到 初始的 XHR 对象, 我看你源码是在 要开始 upload 那一步的时候才创建的 xhr 对象

**Comment by lian-yue** [comment]
@evolutionjay 加上判断啊    `filter-input` 事件不光是 添加， 修改 删除 也会触发
```js
if (newFile && newFile.xhr && !newFile.xhr.withCredentials) {
    newFile.xhr.withCredentials = true
}
```
