### ISSUE TITLE
点击上传按钮后要等待很久才出来选择文件的界面

### ISSUE THREAD

**Issue by h3remi7** [lian-yue/vue-upload-component#13]
不知道是什么问题导致的，readme中的example页面也是 得等个好几秒才出来选择页面

**Comment by lian-yue** [comment]
@h3remi7    这个问题我遇到了 很多次  浏览器的锅  各个浏览器 相应时间不同  chrome 容易出现好几秒才响应  而且不是每次都是好几秒  时不时不正常 一般都正常的

**Comment by h3remi7** [comment]
直接用<input type="file">好像挺正常的？

**Comment by sajiang** [comment]
我的chrome也是点了之后好久才出来选择文件的界面，每次都这样

**Comment by sajiang** [comment]
给作者一点参考：http://www.tuicool.com/articles/vYfYVnf

**Comment by lian-yue** [comment]
@sajiang  这个是浏览器的锅

accept 可以自定义 的  演示下面有 定义 accept 的输入框


https://lian-yue.github.io/vue-upload-component/

**Comment by h3remi7** [comment]
@lian-yue 好像在firefox下 吧这个component放在button标签里面无法触发upload的click事件.chrome下可以

**Comment by lian-yue** [comment]
@h3remi7   你见过谁吧 <input > 放在   button 标签里 就像 吧  <a> 放在  button标签里一样。。。。 按钮里面不能再有按钮

**Comment by h3remi7** [comment]
@lian-yue 原来如此0 0！主要看默认样式以为是个文字标签（ 
于是就放进button里了。。0 0 是我蠢了
