### ISSUE TITLE
Ability to use custom component as trigger

### ISSUE THREAD

**Issue by tegola** [lian-yue/vue-upload-component#135]
Hello,
I'm trying to use a child element (or a custom component) to trigger the filer picker window, like this:

```html
<uploader>
  <button type="button">Browse</button>
</uploader>
```

However, this doesn't seem to work, while this works:

```html
<uploader>Browse</uploader>
```

Is there a way I can accomplish this?

Thanks

**Comment by lian-yue** [comment]
```html
<label for="file">Browse</label>
```

**Comment by tegola** [comment]
I don't get it. What is "file"? The input id?

Anyway, what if I wanted to use a custom button component, like this?

```html
<uploader>
  <my-button size="lg">Browse</my-button>
</uploader>
```

**Comment by feedgit** [comment]
@tegola You can keep your 
```
<file-upload
          extensions="gif,jpg,jpeg,png,webp"
          accept="image/png,image/gif,image/jpeg,image/webp"
          name="avatar"
          class="btn btn-primary"
          post-action="/upload/post"
          :drop="!edit"
          v-model="files"
          @input-filter="inputFilter"
          @input-file="inputFile"
          ref="upload">
          Upload avatar
      </file-upload>
```
and add your custom button example:
`<label for="file">Browse</label>`

**Comment by tegola** [comment]
Sorry guys, I appreciate your time, but I still don't get it. Can you please give me a full usage example of using the uploader component with a custom element or component?

Thanks

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/

**Comment by tegola** [comment]
Sorry for the delay, I'll have a look tomorrow. At first look though, this doesn't sound right to me.

First, `file` (as in `label for="file"`) is only suited for pages where there is only one uploader and its id is `file`. I am working on a single page application where two uploaders could be shown at the same time.

Second, even If I was only showing one uploader, I would end up with this markup:

```html
<label for="file">
  <my-button>Browse</my-button>
</label>
```

which, in turn, would become:
```html
<label for="file">
  <button class="my-btn">Browse</button>
</label>
```
and while this is clearly invalid html, I'm not sure it won't work (again, I'll try tomorrow).

I was expecting an hook on the component, like `$uploader.pick` or something like that.

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/en/documents#options-props-input-id
```html
<label for="file2">
  <button class="my-btn">Browse</button>
</label>
```
```html
<file-upload input-id="file2"> Browse </file-upload>
```

**Comment by tegola** [comment]
Thanks for your support, but that doesn't work with a custom component.

While this works:
```html
<uploader input-id="myuploader"></uploader>
<label for="myuploader">
  Browse
</label>
```

These two don't:
```html
<uploader input-id="myuploader"></uploader>
<label for="myuploader">
  <button type="button">Browse</button>
</label>
```
```html
<uploader input-id="myuploader"></uploader>
<label for="myuploader">
  <my-button-component>Browse</my-button-component>
</label>
```

I'm still looking for a solution.

**Comment by silvalexandre** [comment]
Hi, I just ran into this same problem.
A workaround for now is: 

```html
<uploader input-id="myuploader"></uploader>
<my-button-component onclick="document.getElementById('myuploader').click()">Browse</my-button-component>
```

**Comment by tegola** [comment]
We've come up with a similar workaround:

```html
<uploader ref="uploader"></uploader>
<my-button @click="$refs.uploader.$el.$children[0].click()`>Browse</my-button>
```

Your `click()` is actually neater (and makes sense, since the uploader renders a label), but I like `$refs` more than ids, so I'm using a mix of the two.

Thanks
