### ISSUE TITLE
存在xss

### ISSUE THREAD

**Issue by QJX** [lian-yue/vue-upload-component#136]
在不支持ajax上传文件的浏览器如ie9，如果后台返回的文本包含脚本，如<scipt>alert(666)</script>，使用该组件上传后将会弹出666。如果后台返回的类型改为text/plain，得到的数据将会多出pre标签，原因是用了innerHTML。

**Comment by lian-yue** [comment]
你自己的服务器返回的数据内容都不能控制么？

**Comment by jimyuan** [comment]
日防夜防，家贼难防，哈哈哈

**Comment by QJX** [comment]
如上传一个文件，需要返回文件里的内容呢

**Comment by lian-yue** [comment]
@QJX 
那也是自己上传 xss 到自己 不会影响到别人 何况 你不清楚文件内容 你不 base64编码么， 然后回来了才 解码

如果是 png 什么的 😂2进制 怎么返回啊
