### ISSUE TITLE
vue 2.0中无法使用events，现在的版本是不是不支持2.0？

### ISSUE THREAD

**Issue by crazy0x** [lian-yue/vue-upload-component#14]

**Comment by lian-yue** [comment]
vue 2.0 请使用 
https://github.com/lian-yue/vue-upload-component/tree/2.0

2.0 的分支

**Comment by crazy0x** [comment]
您好，我目前使用的是这个分支，但是events中的回调似乎都失效了，我要如何去注册并使用这些回调？

`events: {
        add(file, component) {
            console.log('add');
            if (this.auto) {
                component.active = true;
            }
            file.headers['X-Filename'] = encodeURIComponent(file.name)
            file.data.finename = file.name

            // file.putAction = 'xxx'
            // file.postAction = 'xxx'
        },
        progress(file, component) {
            console.log('progress ' + file.progress);
        },
        after(file, component) {
            console.log('after');
        },
        before(file, component) {
            console.log('before');
        }
    }`

**Comment by lian-yue** [comment]
vue 2   不支持 events

https://github.com/vuejs/vue/issues/2873
events deprecated, since no more event propaga


 需要 events 作为属性传入 才行

```js
var events  = {
  add(file, component) {
    console.log('add');
  }
}
```

```html
<file-upload  :events=events></file-upload>
```


@crazy0x

**Comment by crazy0x** [comment]
@lian-yue 感谢解答，确实解决了问题，其实已经在example中写得很全了，是我没仔细看2.0分支的example。
