### ISSUE TITLE
Permit capture attribute

### ISSUE THREAD

**Issue by cfbutt** [lian-yue/vue-upload-component#141]
Thanks for sharing the vue-upload-component!

I would like to use a `capture `attribute on the input in order to open directly the users camera (see [https://www.w3.org/TR/html-media-capture/#example-1](https://www.w3.org/TR/html-media-capture/#example-1)). 
Actually this option is not supported by vue-upload-component.

**Comment by lian-yue** [comment]
Attributes already supported >= `2.8.2`

**Comment by cfbutt** [comment]
Thanks a lot!
