### ISSUE TITLE
ie9下，data传递到后台为空

### ISSUE THREAD

**Issue by zhanghong0603** [lian-yue/vue-upload-component#151]
ie10和ie11下正常，ie9下data传递到后台为空或者没有传到后台是怎么回事呢？期待解答。

**Comment by zhanghong0603** [comment]
找到原因了，在uploadHtml4()中，缺少input.value = value，加上ok了。

**Comment by lian-yue** [comment]
https://github.com/lian-yue/vue-upload-component/blob/master/src/FileUpload.vue#L1048

我记得 以前就修复了这问题了  你用的老版本？
