### ISSUE TITLE
Server examples

### ISSUE THREAD

**Issue by lagden** [lian-yue/vue-upload-component#153]
Could you provide any backend example when we are using chunks?

- [ ] nodejs
- [ ] php
- [ ] ruby

etc...

Tks!

**Comment by josec89** [comment]
Hey,

There is a [section in the documentation](https://lian-yue.github.io/vue-upload-component/#/en/documents#getting-started-chunk-upload) about `chunk upload` although there is indeed no _real example_.

You can check the _dummy_ example we have in the code for the examples:
https://github.com/lian-yue/vue-upload-component/blob/master/src/utils/chunkUpload.js
The upload happens in 3 steps:

## start (`chunkUploadStart`)

In this step your backend needs to generate a `unique id` and prepare whatever you are going to use to store all the chunks

## upload (`chunkUploadPart`)

In this step your backend needs to store every chunk in the container using the `unique id` that is sent from the FE

## finish (`chunkUploadFinish `)

In this step your backend needs to wrap it all, generate a file out of all the chunks associated to the `unique id` and return it. You will probably want to clean up in this step too

-----

Notice there is another endpoint which will be determinate which step it is and will redirect to the right backend step method.
Also notice this example is totally dummy and we don't really generate a valid file, you should check [File system docs](https://nodejs.org/api/fs.html) to actually generate a file.

Hope it helped :)

**Comment by lagden** [comment]
@josec89 tks!
