### ISSUE TITLE
How to retrieve the backend response ?

### ISSUE THREAD

**Issue by ssouron** [lian-yue/vue-upload-component#16]
Hello.

I'm trying to implement your fabulous component in an application. All is working very well to choose files, and to send them via a post request. In my backend (under Laravel), I made a route that handles it and which is storing the uploaded files successfully. I made that post php route responding with each stored file path. My question is how, from the files array props, can I get these responded file paths in my frontend if I need it ?

Thank you very much for your work.

**Comment by lian-yue** [comment]
vue 1.x  FileUpload.files[0].data

vue 2.x  FileUpload.files[0].response


Response data content

**Comment by lian-yue** [comment]
vue 1.x  FileUpload.files[0].data

vue 2.x  FileUpload.files[0].response


Response data content

**Comment by ssouron** [comment]
Thank you very much !

I tried `files[x].data`, but I was under Vue 2 ...

**Comment by lian-yue** [comment]
@ssouron 

Documentation error
`data` is the request content
