### ISSUE TITLE
How to show upload progress when using custom-action?

### ISSUE THREAD

**Issue by stacieweff** [lian-yue/vue-upload-component#161]
file.progress seems to be undefined when trying to use a progress bar through a custom-action posting through axios.  
file.active and file.success are both working. But file.size, file.progress, etc. are not using the code from the example. 
Is something else needed when using a custom-action?

```
 <div class="att-upload-meter" v-if="file.active || file.progress !== '0.00'" :style="{width: file.progress + '%'}">{{file.progress}}%
</div>

```
```
  inputFile (newFile, oldFile) {
      if (newFile.progress !== oldFile.progress) {
        // progress
        console.log('progress', newFile.progress, newFile)
      }
}
```

**Comment by weituotian** [comment]
why close? what are you doing？

**Comment by allaghi** [comment]
Hi @stacieweff 
Have a nice day,
I am facing same issue , if you got the correct way to do it , please share us the solution.
Thanks in advance.
