### ISSUE TITLE
Uploaded all files in queue hook

### ISSUE THREAD

**Issue by blyleven** [lian-yue/vue-upload-component#177]
Hi! 

I've been looking everywhere but I can't seem to find a working solution. Is there some way I can check if all files in the queue are uploaded? I want to make a post request when all files are uploaded, so I've tried 

` if(this.$refs.audioUploader && this.$refs.audioUploader.uploaded) {
    // axios.post here
}`

But even when I've uploaded only 1 single file, this will be executed twice.

Anybody got an idea?

Thanks!

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/en/documents#instance-data-uploaded

**Comment by lian-yue** [comment]
if(this.$refs.audioUploader && this.$refs.audioUploader.value.length && this.$refs.audioUploader.uploaded) { // axios.post here }
