### ISSUE TITLE
服务器返回500，上传一直在重试

### ISSUE THREAD

**Issue by weituotian** [lian-yue/vue-upload-component#184]
![q -20180510222737](https://user-images.githubusercontent.com/7270968/39874782-64e2b622-54a1-11e8-9071-b6d044199c07.png)

怎么控制出错不再上传？

**Comment by weituotian** [comment]
在`inputFile: function (newFile, oldFile) `
中使用`newFile.success = false;`就会变成这样

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E4%BA%8B%E4%BB%B6-input-file
> 事件内可使用 update, add, remove, clear 方法
事件内不可修改 newFile 对象
事件内不可修改 oldFile 对象

**Comment by weituotian** [comment]
但是我修改 newFile.error 去自定义我的错误信息，就没问题，
那有正确的方法修改 inputFile 吗？

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E5%AE%9E%E4%BE%8B-%E6%96%B9%E6%B3%95-update


使用 update 方法 修改 newFile 啊

这下面 有  的使用的演示啊
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E4%BA%8B%E4%BB%B6-input-file

**Comment by weituotian** [comment]
这思路跟不上啊。
