### ISSUE TITLE
[Question] Is possible to send as `multipart/form-data` on custom action?

### ISSUE THREAD

**Issue by amandiobm** [lian-yue/vue-upload-component#187]
Hello guys, 

I'm using the custom action prop, but the request is not as a `enctype="multipart/form-data"`, In that case my server won't be able to handle the files.

**Comment by Imboga** [comment]
Hi there, how did you resolve it? I'm trying to submit the whole file object to vuex action but no luck so far, I'm not receiving a file at all.
