### ISSUE TITLE
Convert into File from an Image URL

### ISSUE THREAD

**Issue by tagmetag** [lian-yue/vue-upload-component#189]
Hello, i want to Convert into File from an Image URL in order to trigger add() event:

I tried:

`let file = new window.File(['http://localhost:8000/media/users/2/19_227.jpg'], 'image.jpg', { type: 'image/jpg' })`
`this.$refs.upload.add(file)`

Blob which is rendered is not work.

**Comment by igor-chepurnoi** [comment]
Hi @feedgit , How you resolve this issue?

**Comment by koslo** [comment]
Same problem here. 
I find no way to show always uploaded images. (for the edit view of the data model)

**Comment by brolnickij** [comment]
UP
