### ISSUE TITLE
可否让这个组件支持jwt？

### ISSUE THREAD

**Issue by leenux** [lian-yue/vue-upload-component#2]
上传时 往往需要认证 不能谁都上传
感谢

**Comment by lian-yue** [comment]
@leenux    有2个参数 可以定义 token   request.headers 附加header 头  request.data 附加数据 


针对每个文件独立设置的
fiies[0].request.headers
fiies[0].request.data 

https://github.com/lian-yue/vue-upload-component/blob/master/src/example.js#L43
