### ISSUE TITLE
insert new files to old files array by prop `add-index`

### ISSUE THREAD

**Issue by black-black-cat** [lian-yue/vue-upload-component#212]
Hey buddy.

Is this ok in line 450 in `FileUpLoad.vue` ? 

<img width="349" alt="10" src="https://user-images.githubusercontent.com/15521864/42407656-edaff900-81f2-11e8-8c7f-1618a7557299.png">

**Comment by igor-chepurnoi** [comment]
How can I add the file to specific index?

**Comment by lian-yue** [comment]
@igor-chepurnoi  yes
