### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by TunaYagci** [lian-yue/vue-upload-component#219]
We've detected memory leaks in this component. I'll provide a jsFiddle soon.

**Comment by TunaYagci** [comment]
https://jsfiddle.net/TunaYagci/wtpuevc6/1509/

1. For testing, get a dump when you land the page
2. Route to `foo`
3. Route back to `home`
4. Get another dump here

When you compare those dumps you'll see `FileUpload` still lives.

![screen shot 2018-08-07 at 15 29 30](https://user-images.githubusercontent.com/11725130/43775870-cb04198c-9a56-11e8-9de5-51d56cf3daae.png)
![screen shot 2018-08-07 at 15 29 57](https://user-images.githubusercontent.com/11725130/43775871-cbb51912-9a56-11e8-8526-f825011180f5.png)

**Comment by TunaYagci** [comment]
This probably caused because of `change` function in `InputFile.vue`. Why are you manually destroying and constructing it again on every change? That doesn't feel right.

**Comment by TunaYagci** [comment]
Is the leak resolved?

**Comment by lian-yue** [comment]
Has been resolved.

Only ie9 still exists 

https://github.com/lian-yue/vue-upload-component/commit/a969e16bc07a4cd0a5e865dfea99aeaff3e3a9dc#diff-19d3231fd30fc2ee6ac99ab69ec55404

**Comment by TunaYagci** [comment]
Just curious, how did you find out that was causing it? I'm trying to create a tool that shows which component leaks.

**Comment by lian-yue** [comment]
`$destroy` should have a problem
Will not destroy immediately

**Comment by TunaYagci** [comment]
That actually seems to be fixed. Thanks!
