### ISSUE TITLE
直接使用你的component修改测试有两个引入的问题  新手一枚 请指教

### ISSUE THREAD

**Issue by Jonyezog** [lian-yue/vue-upload-component#223]
//import Cropper from 'cropperjs'
 // import FileUpload from 'vue-upload-component'
这两地方的引入没有找到component在哪里

**Comment by Jonyezog** [comment]
Failed to compile.

./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/components/upload.vue
Module not found: Error: Can't resolve 'cropperjs' in 'F:\vue\vuetest\vuetest\src\pages\components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/components/upload.vue 308:0-32
 @ ./src/pages/components/upload.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by lian-yue** [comment]
https://github.com/fengyuanchen/cropperjs

使用  externals  外部扩展  和   alias 别名
https://github.com/lian-yue/vue-upload-component/blob/master/webpack.config.js#L44
