### ISSUE TITLE
Uploading a file puts it in the first file-upload component, not the right one

### ISSUE THREAD

**Issue by Lordmau5** [lian-yue/vue-upload-component#227]
So back in version 2.8.11 it worked just fine.
Ever since 2.8.12 or 2.8.13, it automatically runs the specific @input or @input-file method on the **first** file-upload component.

Version 2.8.12+:
https://i.imgur.com/qdji33r.gifv

Version 2.8.11:
https://i.imgur.com/3M4GSNV.gifv

**Comment by lian-yue** [comment]
```html
<file-upload input-id ="file-icon-18">1</file-upload>
<file-upload input-id="file-icon-32">2</file-upload>
<file-upload input-id="file-icon-72">3</file-upload>
```

https://lian-yue.github.io/vue-upload-component/#/en/examples/multiple
