### ISSUE TITLE
vue2.0 using tree2.0 examples reports error

### ISSUE THREAD

**Issue by LazyNeo** [lian-yue/vue-upload-component#23]
click item and choose an file to upload then console shows msgs:

> vue-upload-component.js?6302:856 Uncaught TypeError: Cannot set property 'h9wltv39qtuvqondzf5gq4cxr' of undefined

code follows:

`
<template>
  <div class="">
    <file-upload title="Add upload files" post-action="http://oss.aliyuncs.com"></file-upload>
  </div>
</template>
<script>
import FileUpload from 'vue-upload-component'
export default{
  data(){
    return {}
  },
  methods:{
  },
  components:{
    FileUpload
  }
}
</script>
`

**Comment by joturako** [comment]
```
import FileUpload from 'vue-upload-component' 

export default{ 

data(){

 return {}

}, 

methods:{ },

components:{ FileUpload } 

}
```
