### ISSUE TITLE
How can I change object to filelist?

### ISSUE THREAD

**Issue by galaxyuliana** [lian-yue/vue-upload-component#234]
Hi,

*I'm using .NET for backend.

I used input tag for attachment `(<input` `type="file">)` and changed to this component.

When attaching files, input tag saves as filelist and component saves as object.

I send filelist to backend and backend sends email with attachments.

so, is there any way to make object to filelist?

Thank you

**Comment by galaxyuliana** [comment]
Or is there any ways to save temp files?

**Comment by diegotejadav** [comment]
I can't understand you @galaxyuliana, 
What are you getting and what are you expecting?
