### ISSUE TITLE
上传无扩展名的文件失败

### ISSUE THREAD

**Issue by sakila1012** [lian-yue/vue-upload-component#240]
![image](https://user-images.githubusercontent.com/12171330/47974182-60bd0b00-e0e3-11e8-8cb0-830d7302aaf2.png)
无法上传，求原因

**Comment by lian-yue** [comment]
extension
 参数留空

**Comment by sakila1012** [comment]
@lian-yue 是不是在data> extensions: 'gif,png,jpg, , '这样添加
另外，我尝试将extensions设置为"*"可以上传所有的文件，但组件提示正则错误

**Comment by sakila1012** [comment]
将 extension 设置为 undefined
