### ISSUE TITLE
response里面没有header头信息

### ISSUE THREAD

**Issue by welllog** [lian-yue/vue-upload-component#249]
怎么获取上传成功后的响应头信息

**Comment by lian-yue** [comment]
file.xhr 里面有

**Comment by welllog** [comment]
拿不到，file.xhr没有这个属性，调用file.xhr.getAllResponseHeaders也获取不到。只好把上传方法复制出来改改了

**Comment by welllog** [comment]
谢谢，已经通过file.xhr获取到responseHeader
