### ISSUE TITLE
IE10 无法再次上传同一个文件，上传同一个文件不会触发后台请求？

### ISSUE THREAD

**Issue by sakila1012** [lian-yue/vue-upload-component#257]
上传任意一个文件，上传成功后，不刷新页面，再次上传同一个文件，不会触发请求？
是不是bug?

**Comment by lian-yue** [comment]
重新添加的还是？同一条数据
同一条 吧  两个状态初始化
file.error  = ""
file.success = false

**Comment by sakila1012** [comment]
@lian-yue 
重新添加，上传同一个文件，没有反应，上传其他的文件就可以。我查了change事件没有触发。没有向后台发送请求，也就没有 file 状态 
测试例子好像也不行。

**Comment by CanvasShoeJson** [comment]
同问，遇到同样的问题了。

**Comment by JasonGaoG** [comment]
same issue .any update please?
