### ISSUE TITLE
2.0.0-beta reports error

### ISSUE THREAD

**Issue by aliseph** [lian-yue/vue-upload-component#26]
> Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "files"  (found in component <file-upload>)
![image](https://cloud.githubusercontent.com/assets/1501312/20834041/e1bfcc46-b8cd-11e6-9a67-535c62c16d16.png)

**Comment by lian-yue** [comment]
Fixed
