### ISSUE TITLE
Component is not a constructor

### ISSUE THREAD

**Issue by sureshamk** [lian-yue/vue-upload-component#28]
im getting err  Component is not a constructor

**Comment by suifengfengye** [comment]
I'm meet the same problem!

**Comment by suifengfengye** [comment]
I have the same problem!

Now, I modify the FileUpload.vue.
`// var Component = this.$options.components.inputFile;//after vue@2.1.x，Component is not a constructor anymore!
      var Component = this.$options.components.inputFile._Ctor[0];`

Although this not a good way, but it can resolved this problem!

This problem cause by vue 2.1.x, if you change vue to 2.0.x, you will never see this problem.

**Comment by lian-yue** [comment]
@suifengfengye 

@sureshamk 

The latest version has been repaired
