### ISSUE TITLE
存在不发put请求的配置项吗？

### ISSUE THREAD

**Issue by foxpsd** [lian-yue/vue-upload-component#29]
看起来目前是默认发put请求？那设置里的postAction有何作用呢？

**Comment by foxpsd** [comment]
希望可以简单加一下对配置项的解释~不然实在是很难用

**Comment by lian-yue** [comment]
不设置 putAction  只设置  postAction 就好了
```
<file-upload post-action="/post' ....></file-upload>
```

**Comment by foxpsd** [comment]
感谢！这个试出来了。另外，不知道存不存在配置项可以修改发送方式？从复杂 CORS 请求改为简单 CORS请求，即不发送OPTION preflight预请求，直接发 POST？

**Comment by lian-yue** [comment]
@foxpsd  跨域的话啊  CORS 是浏览器自动控制的 

CORS需要浏览器和服务器同时支持。目前，所有浏览器都支持该功能，IE浏览器不能低于IE10。
整个CORS通信过程，都是浏览器自动完成，不需要用户参与。对于开发者来说，CORS通信与同源的AJAX通信没有差别，代码完全一样。浏览器一旦发现AJAX请求跨源，就会自动添加一些附加的头信息，有时还会多出一次附加的请求，但用户不会有感觉。

**Comment by foxpsd** [comment]
@lian-yue 我发现了，之所以会发送OPTION预请求，是因为请求中出现了`Accept`，`Accept-Language`，`Content-Language`，`Last-Event-ID`，`Content-Type`这些请求头之外的请求头。在我们这个框架中，就是在源码508行手动指定的X-Requested-With这个请求头。目前后台接口比较老旧且无人更新，无法针对OPTION预请求返回Access-Control-Allow-Headers返回头，来合法化X-Requested-With请求头，导致后续请求无法顺利发出。看起来除了修改后台接口没有解决的办法。3Q anyway~

**Comment by lian-yue** [comment]
@foxpsd   你是跨域 还是同域下 发生的

**Comment by foxpsd** [comment]
@lian-yue 接口是同域

**Comment by lian-yue** [comment]
@foxpsd   知道了 我修复下   估计浏览器 问题   我的同域下自定义 header 不会出现  OPTION
