### ISSUE TITLE
包下载后，无法加载组件

### ISSUE THREAD

**Issue by Rachelin** [lian-yue/vue-upload-component#3]
包下载后，我用browsrify无法build成功。错误信息是：
```
Error: Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/vue-loader/lib/style-rewriter.js!./../node_modules/vue-loader/lib/selector.js?type=style&index=0!./FileUpload.vue'
```
我用的osx 10.10.5，项目是用browserify ＋ vue。
我担心是不是没有加载依赖包，npm install之后，还是报错。麻烦@lian-yue 帮忙看一下。

**Comment by lian-yue** [comment]
@Rachelin 
我用的 webpack

browsrify  不清楚  browsrify 配置到能加载 vue 文件不

直接引入  也不行么  
/src/FileUpload.vue
