### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by rhysstubbs** [lian-yue/vue-upload-component#300]
Using a "custom-action" which successfully returns, but as soon as the promise resolves I get the error `Cannot read property 'id' of undefined`. What should the custom-action be returning?

Here is the method that gets called for the custom-action, it returns a promise resolved from axios:

```
uploadImage: async function (file, component) {

     return await this.$store.dispatch('entities/clients/uploadLogo', { clientId: this.data.id, file: file });
},
```

**Comment by lian-yue** [comment]
`this.data.id `
Are you sure he exists?

**Comment by rhysstubbs** [comment]
The action successfully resolves, which would not be possibly if `this.data.id` was undefined or null

**Comment by rhysstubbs** [comment]
The error appears using the following in the template:

```
<td v-if="file.error">{{file.error}}</td>
```

No errors are thrown from the custom-action function

**Comment by rhysstubbs** [comment]
Closing due to my own stupidness, the async function was swallowing the exception, it was my own code that was failing.
