### ISSUE TITLE
询问一下，update函数为什么触发多次？

### ISSUE THREAD

**Issue by 233cy** [lian-yue/vue-upload-component#323]
![image](https://user-images.githubusercontent.com/29916783/66727854-4d2e2e80-ee74-11e9-8820-213d530402cd.png)
![image](https://user-images.githubusercontent.com/29916783/66727867-57e8c380-ee74-11e9-9605-42642f54160f.png)
同样的代码本来会触发四次，不知道怎么了突然就又只触发两次了。 @lukeb

**Comment by lian-yue** [comment]
激活上传 
会自动上传
更新上传进度 更新响应结果
