### ISSUE TITLE
How to upload using custom action

### ISSUE THREAD

**Issue by lucianobosco** [lian-yue/vue-upload-component#341]
Hi there! I'm trying to perform the upload through custom action by using vuex
```
async customAction (file, component) {
       return this.storeResource(file)
}
```
On the vuex side, the action is doing
```
storeResource ({ commit }, file) {
       axios({
              method: 'post',
              url: '/files/store',
              headers: { 'Content-Type': 'multipart/form-data' },
              data: file
       })
       .then(response => {
              // do something
       })
 },
```
In my case, I'm using Laravel as API, so I'm just trying to get the file from `$request->file` but there is no file at all.

Am I missing something? Where is the file itself supposed to be attached when using the custom action? I saw that default post-action sends a binary file, but not the same in custom action.

Any tips or help will be really appreciated.

**Comment by AnggaDAR** [comment]
hello there, since you are using 'multipart/form-data'

**Comment by topada** [comment]
**file.file**—because why not waste my whole Thursday :-)
