### ISSUE TITLE
请问如何带上cookie呢，xhr无法修改，:header无法设置Cookie。

### ISSUE THREAD

**Issue by rexKen** [lian-yue/vue-upload-component#344]

**Comment by rexKen** [comment]
因为项目赶的原因，我暴力修改了源码，如果可以，希望能更新下呢，看遍文档都找不到解决方法很尴尬。还是谢谢大佬开源的工具。

**Comment by lian-yue** [comment]
```
<file-upload @input-filter="inputFilter">Add</file-upload>

``

```
  methods: {
    inputFilter(newFile, oldFile, prevent) {
       if (newFile && oldFile && newFile.xhr && !oldFile.xhr) {
          newFile.xhr.withCredentials = true
      }
   }


```
