### ISSUE TITLE
vue中引入vue-upload-component在ie浏览器中出现问题

### ISSUE THREAD

**Issue by w609544721** [lian-yue/vue-upload-component#352]
如图：request Header中Content-Type为multipart/form-data;response Header中content-type:text/html; charset=UTF-8，此种情况在chrome浏览器中正常,在ie浏览器中出现如下问题：
![企业微信截图_1590127513655(1)](https://user-images.githubusercontent.com/32625393/83856444-29de2980-a74c-11ea-9c10-bfd045556d56.png)
请问应如何解决，望尽快得到回复，不胜感激！！！

**Comment by w609544721** [comment]
如果图片看不到请及时联系我

**Comment by iUUCoder** [comment]
服务端 response 的 content-type 设置为 text/html 即可。
