### ISSUE TITLE
一个页面使用多个组件会点击某一个上传会同时触发其他的上传

### ISSUE THREAD

**Issue by xuedongyuan928** [lian-yue/vue-upload-component#355]

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E5%B1%9E%E6%80%A7-input-id

https://github.com/lian-yue/vue-upload-component/blob/master/docs/views/examples/Multiple.vue
