### ISSUE TITLE
How to get response in TypeScript

### ISSUE THREAD

**Issue by RoelWeerdenburg** [lian-yue/vue-upload-component#369]
How can I get the response when using TypeScript?
It does not seem to return the JSON response.

**Comment by RoelWeerdenburg** [comment]
Nevermind.
The response stated success as false. Because of another validation.
Then you do not get other response values back.

**Comment by lian-yue** [comment]
```html
<div v-for="file of files">
<span>{{file.response}}</span>
</div>
```
