### ISSUE TITLE
how to limit selectable files to gpx extension

### ISSUE THREAD

**Issue by udos** [lian-yue/vue-upload-component#375]
hi,

using the demo

- https://lian-yue.github.io/vue-upload-component/#/en/examples/full

I tried to limit selectable files to only allow _**gpx**_ files, setting _Accept_ to **_application/gpx+xml_** and _Extensions_ to _**gpx**_:
![image](https://user-images.githubusercontent.com/141107/101987069-1f1fc680-3c92-11eb-8d90-5032a272edfe.png)

unfortunately this still allows all files to be selectable:
![image](https://user-images.githubusercontent.com/141107/101987180-ce5c9d80-3c92-11eb-9979-f898c8a288c7.png)

I guess I'm missing something :| how can I limit the selectable files to **_gpx_** files only?

thanks!

note: I attached an example gpx file (which is pure xml) -> **_IMPORTANT: I had to change extension to txt because github does not support gpx file type..._** -> [000.txt](https://github.com/lian-yue/vue-upload-component/files/5683269/000.txt)

**Comment by lian-yue** [comment]
`application/gpx+xml` is not a common type, most browsers do not support `accept` does not support

Can't prevent selection
You can filter out files that are not `.gpx` from the `@input-filter` filter

```html
<file-upload @input-filter="inputFilter"></file-upload>
```

```js
{
  // ....
  methods: {
    inputFilter(newFile, oldFile, prevent) {
      if (newFile && !oldFile && newFile.name.search(/\.gpx$/i) === -1) {
        return prevent()
      }
    }
  }
 // ....
}
```

https://github.com/lian-yue/vue-upload-component/blob/master/docs/views/examples/Avatar.vue#L161
