### ISSUE TITLE
一个页面多处上传组件的问题

### ISSUE THREAD

**Issue by wangwenbo000** [lian-yue/vue-upload-component#38]
作者好，如果一个页面上有多个上传组件，已经将组件name ref属性内容区分，但是触发上传后会同时触发该页面其他的上传组件。是否是我的处理思路有问题呢

**Comment by lian-yue** [comment]
https://github.com/lian-yue/vue-upload-component/blob/2.0/example/Multi.vue

**Comment by alanzyy** [comment]
一定要设置inputid即可

**Comment by alanzyy** [comment]
> https://github.com/lian-yue/vue-upload-component/blob/2.0/example/Multi.vue

链接不可用
