### ISSUE TITLE
Not allow to upload xls/ xlsx

### ISSUE THREAD

**Issue by roytom** [lian-yue/vue-upload-component#380]
` metaData: {
          accept: 'image/png,image/gif,image/jpeg,image/webp,application/pdf,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-powerpoint,text/plain',
          extensions: 'gif,jpg,jpeg,png,webp,pdf,xls,xlsx,doc,docx,ppt,txt',
          size: 1024 * 1024 * 1000,
          multiple: true,
          directory: false,
          drop: true,
          dropDirectory: false,
          addIndex: true,
          thread: 3,
          name: 'file',
          postAction: '/campaign/uploadIo',
          putAction: '',
          headers: {
            'X-Csrf-Token': 'xxxx'
          }
        },`

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/en/documents#options-events-input-filter
