### ISSUE TITLE
How to send files via GraphQL?

### ISSUE THREAD

**Issue by vladninja** [lian-yue/vue-upload-component#398]
Hi. 
Currently, we are having a post-action/put-action props, which are strings and must be a URL for the classic REST API.
But, if I need to use a GraphQL, not a REST API, I can't modify this to call a custom function or something like this (GQL has only one URL, but different mutations and queries, so there is no possibility to send files via GQL, not REST API).

**Comment by masterkain** [comment]
hello, how did you solve?

**Comment by TargiX** [comment]
Hey @vladninja , I need to use graphql to upload files, can you please give a tip how you solved, if you did. Thanks!
