### ISSUE TITLE
vue2.0怎么触发process事件，照着例子来也没触发

### ISSUE THREAD

**Issue by 15697289437** [lian-yue/vue-upload-component#40]

**Comment by lian-yue** [comment]
html5 才会触发 process 事件

**Comment by 15697289437** [comment]
我看了默认就是html5的

**Comment by lian-yue** [comment]
@15697289437 

在 ｀vue-upload-component｀  的目录下 运行命令  `npm run dev`  用 chrome 打开 http://localhost:8000 测试 看能触发  process 事件 不
目前已知 的只有 ie9 无法触发
