### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by xingchch** [lian-yue/vue-upload-component#41]
npm install 然后
如下方法导入组件
import FileUploadComponent from 'node_modules/vue-file-upload-component/vue.file-upload.js'
运行console 显示如题错误。

**Comment by xingchch** [comment]
我用的vue2.0

**Comment by lian-yue** [comment]
`vue-file-upload-component` 不是我的组件
https://github.com/james2doyle/vue-file-upload-component



```
import VueUploadComponent from 'vue-upload-component'
```
