### ISSUE TITLE
上传文件类型的限制，在拖拽上传的时候不能生效

### ISSUE THREAD

**Issue by waveheart** [lian-yue/vue-upload-component#414]
## options中限制了文件类型
![image](https://user-images.githubusercontent.com/25602259/147536586-a8d74555-3fb7-4e81-8367-776a2b4acd2b.png)

## 手动选择，限制是有效的
![image](https://user-images.githubusercontent.com/25602259/147536664-b84797b3-f344-4482-926f-e74772cb71b8.png)

## 拖动一个EXCEL
![image](https://user-images.githubusercontent.com/25602259/147536718-1a2dbb25-63d6-4f24-9fc0-88d1007f3d9b.png)

## 依然进入了列表
![image](https://user-images.githubusercontent.com/25602259/147536747-1b0909db-837d-4367-97de-6de465154fe3.png)

## 期望，禁止拖入非法类型的文件，或者可以自动过滤掉不符合条件的文件

**Comment by lian-yue** [comment]
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#%E9%80%89%E9%A1%B9-%E4%BA%8B%E4%BB%B6-input-filter
