### ISSUE TITLE
:headers not used in chunk mode

### ISSUE THREAD

**Issue by GinJus** [lian-yue/vue-upload-component#425]
Hi,

For posting to a Laravel controller I need the X-CSRF-TOKEN token in the header. When :chunk-enabled is set to "false", the :headers variables are used but nut when it set to "true".

How come? I've also tried to add this:
`newFile.headers['X-CSRF-TOKEN'] = this.csrf;`
in the InputFilter.

Thanks.

**Comment by lian-yue** [comment]
```js
 :chunk="{
   header:{"x-csrf-token": "xxx"},
 }
```

https://github.com/lian-yue/vue-upload-component/blob/master/src/FileUpload.vue#L59
