### ISSUE TITLE
关于props

### ISSUE THREAD

**Issue by rainwalkerhu** [lian-yue/vue-upload-component#43]
大佬，可否详细解释下你的组件各个配置，以及组件支持什么功能，例如分片上传啥的，readme写详细点目测会火

**Comment by lian-yue** [comment]
props 属性名应该是简单明了的  英文不怎么好所以 直接简单的写了下
 分片什么的 这不是上传大型文件的组件  所以不会考虑到

**Comment by rainwalkerhu** [comment]
我看了源码勉强能理解了，现在遇到问题是，在add钩子里面触发 component.active = true;或者在父组件this.$refs.upload.active=true都不管用，我已经将组件的ref属性设置为upload，依然没有http请求产生

**Comment by lian-yue** [comment]
你可以试试这样
```
this.$refs.upload.$data.active  = true
```

**Comment by rainwalkerhu** [comment]
可以启动了 。还有一个问题，就是我的上传文件类型需要限制为文档类型，这是我的配置
accept: 'application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/plain,application/pdf',
extensions: 'xlsx,xls,doc,docx,pdf,txt',
在电脑上确实可以限制选择的文件为文档类型，但是在安卓手机上测试时发现还是什么文件都可以，
另外extensions这个属性是用来进一步限制文档的类型的还是？

**Comment by lian-yue** [comment]
@rainwalkerhu    accept 是浏览器 表单自身的属性  看浏览器支持
extensions  是限制文件后缀的   这个所有浏览器都支持
