### ISSUE TITLE
The requested module 'vue-upload-component' does not provide an export named 'default'

### ISSUE THREAD

**Issue by fedottt** [lian-yue/vue-upload-component#458]
The requested module 'vue-upload-component' does not provide an export named 'default'

`<script type="importmap">
		{
			"imports": {
				"vue": "../npm/node_modules/vue/dist/vue.esm-browser.prod.js",
				"vue-upload-component": "../npm/node_modules/vue-upload-component/dist/vue-upload-component.js"
			}
		}
	</script>

<script type="module" src="<?php echo $conf['board_url_js']; ?>/upl.js"></script>
`
 
and upl.js is

`import { createApp, ref } from 'vue'
import { toast } from '/js/toastify.js'
import VueUploadComponent  from 'vue-upload-component'`

**Comment by lian-yue** [comment]
ESM support that has been added with browser, updated to version 3.1.15

```bash
npm i vue-upload-component@3.1.15
```

``` 
https://github.com/lian-yue/vue-upload-component/blob/master/esm.html
https://unpkg.com/vue-upload-component@3.1.15/dist/vue-upload-component.esm.js
```

**Comment by fedottt** [comment]
awesome! 
thk)
