### ISSUE TITLE
老司机，现在这个插件不支持vue2？ 

### ISSUE THREAD

**Issue by zuoye520** [lian-yue/vue-upload-component#47]
我在vue2 服务端渲染时，编译的时候报 window is not defined，
希望老司机能兼容到vue2

**Comment by lian-yue** [comment]
服务端渲染还没测试过 
应该是编译版的问题 你可以试试直接引用
```
import FileUpload from 'vue-upload-component/src/FileUpload.vue'
```

**Comment by zuoye520** [comment]
希望老司机可以支持SSR ！ 辛苦了！！
[https://github.com/vuejs/vue-hackernews-2.0/issues/146](url)

**Comment by zuoye520** [comment]
@lian-yue 
希望老司机能够支持下SSR，辛苦了！
https://github.com/vuejs/vue-hackernews-2.0/issues/146
