### ISSUE TITLE
Error after 2.3.0

### ISSUE THREAD

**Issue by avengerweb** [lian-yue/vue-upload-component#53]
[Vue warn]: Error in callback for watcher "files": "TypeError: Cannot read property 'fgc6n1j1i6sem5vqm06qrggb9' of undefined"

found in

---> <FileUpload>

Update:
+-- vue@2.3.0 
+-- vue-router@2.5.2
+-- vue-template-compiler@2.3.0
`-- vue-upload-component@2.3.0 <- 2.3.0-beta.2

**Comment by antoineherzog** [comment]
i got the error as well.

**Comment by antoineherzog** [comment]
@lian-yue any help?

**Comment by lian-yue** [comment]
fix 
update to 2.3.1
```
  npm install vue-upload-component@2.3.1 --save
```
