### ISSUE TITLE
2.3.0-beta.2之后的版本把单击选择文件改成了双击

### ISSUE THREAD

**Issue by fengxinming** [lian-yue/vue-upload-component#55]
2.3.0-beta.2之后的版本把单击选择文件改成了双击，我已经回退到了2.3.0-beta.2这个版本

**Comment by lian-yue** [comment]
并不是 双击   或许你加了  accept  参数   accept 在某些浏览器上会卡慢

如果不是请给出  浏览器 UA

**Comment by fengxinming** [comment]
@lian-yue 不好意思，五一休假了忘记回复了，确实是有设置accept这个属性，在之前的版本里，如果不设置这个属性在Chrome40+的版本下是正常的，但是在比较新的Chrome上运行就卡了，然后增加了accept这个属性解决这个问题，在2.3.0之后我对比了源码，你把之前的jsx的写法改了template，但是不知道为何我引入项目中就变成了双击打开选择框，为了项目上线，我还是回退回来到原来的版本
