### ISSUE TITLE
can i add a default images or icon for file type that has not image?

### ISSUE THREAD

**Issue by codeitlikemiley** [lian-yue/vue-upload-component#65]
Images when upload already has images attach to it,
how can i add a default image let say for pdf or powerpoint or docs...
anyone know how you may do it thanks

**Comment by lian-yue** [comment]
The component is just a button.
You can add this feature


https://github.com/lian-yue/vue-upload-component/blob/2.0/example/Home.vue#L62
```vue
<td v-if="file.type.substr(0, 6) == 'image/' && file.blob">
    <img :src="file.blob" width="50" height="auto" />
</td>
<td v-else-if="/\.pdf$/i.test(file.name)">
    <img src="http://test.com/icon/pdf.png" width="50" height="auto" />
</td>
<td v-else></td>

```
