### ISSUE TITLE
why do we need put and post? can we only have one method to be use?

### ISSUE THREAD

**Issue by codeitlikemiley** [lian-yue/vue-upload-component#66]
btw im using laravel, on my back end...

Can i leave the put method blank (empty) or post method, 
lets say i only want to upload and not update the files
is that possible thanks for those who will answer...

**Comment by lian-yue** [comment]
`put-action` ` post-action` is an optional parameter
You can fill in one

**Comment by codeitlikemiley** [comment]
ok i get it thanks
