### ISSUE TITLE
Can I use with `<script>`?

### ISSUE THREAD

**Issue by haeyon098** [lian-yue/vue-upload-component#68]
Hi, I want to use it. I don't use `NPM` now. 
so, I tried like this https://jsbin.com/bapatifahi/edit?html,js,console,output

It doesn't work. 
can i use with `<script>` ? 
If i use `vue-uplod-component`, should i use `NPM`?

**Comment by lian-yue** [comment]
You can use `commonjs` to load

**Comment by haeyon098** [comment]
@lian-yue Thank you your comment. But, I don't use `commonjs` in my project and I'm not good front-end programmer. 
So, If it's possible, I wanna use `<script>`. Is it possible? If you reply my question, it helps me a lot.

**Comment by lian-yue** [comment]
@haeyon098 
Updated
https://github.com/lian-yue/vue-upload-component#html

**Comment by haeyon098** [comment]
@lian-yue Thank you !!
