### ISSUE TITLE
你好，请问上传各种状态的回调和上传完成后台返回的数据怎么获取？

### ISSUE THREAD

**Issue by IdyllicFish** [lian-yue/vue-upload-component#70]
你好，请问上传各种状态的回调和上传完成后台返回的数据怎么获取？

**Comment by lian-yue** [comment]
`file.response` 里面

https://github.com/lian-yue/vue-upload-component#props-value

**Comment by songzeng2016** [comment]
inputFile 事件里面 
if (newFile && oldFile) {
          // 更新文件
        
          if (newFile.success !== oldFile.success) {   // 上传成功
            if (newFile.response.code === 200) {  // 判断后台返回的code值
              // 上传成功
            } else {
              // 上传失败
            }
          }
        }
