### ISSUE TITLE
一个页面同时放两个这个组件，只有最后一个能够正常使用？

### ISSUE THREAD

**Issue by 921010wxm** [lian-yue/vue-upload-component#73]
页面中同时放两个上传的v-model对应的也不一样，却只有最后一个能用，问一下这个是什么原因造成的呢？

**Comment by lian-yue** [comment]
`props` 的 `name` 参数 是唯一 相同 不行 需要吧 name 设置成 name="file" name="file2"

**Comment by limeng1900** [comment]
@lian-yue  首先感谢
提个意见：   
input name 唯一设计是个挺大的障碍，比如有多个组件需要input name需要相同的情况

一个页面里放两个组件，上传的Form Data里的文件字段是定死的‘file’（阿里oss存储的要求）,这个字段名又是input的name，但同时放两个name相同的组件时又不能用。

另一种方案需要Form Data里的字段名可以自主修改，而不是直接绑定input的name。

**Comment by limeng1900** [comment]
> @limeng1900 已经不是唯一了 input-id 才是唯一

谢谢回复。
