### ISSUE TITLE
微信浏览器不支持预览？

### ISSUE THREAD

**Issue by Foreverofh** [lian-yue/vue-upload-component#75]

**Comment by lian-yue** [comment]
![b39abae26b694100183cc779d3ee1dd5](https://user-images.githubusercontent.com/6044394/29455267-81e1efd0-844b-11e7-9708-5f2d93d4da8d.png)
![a099170892e8604dc5cd0a7c1a01915a](https://user-images.githubusercontent.com/6044394/29455274-8823f5fa-844b-11e7-9c1c-4a06c7bc3405.png)

测试可以支持预览
