### ISSUE TITLE
Restricted extensions

### ISSUE THREAD

**Issue by mezzaninegold** [lian-yue/vue-upload-component#78]
Is it possible to do Not allowed/restricted extensions rather than allowed extensions?

IWe've got a list of extensions we don't want people to upload.
ace,ade,adp,ani,app,asp,aspx,asx,
bas,bat,cer,chm,cmd,cnt,com,cpl,
crt,csh,der,docm,exe,fxp,gadget,hlp,
hpj,hta,htc,inf,ins,isp,its,jar,
js,jse,ksh,lnk,mad,maf,mag,mam,
maq,mar,mas,mat,mau,mav,maw,mda,
mdb,mde,mdt,mdw,mdz,mht,mhtml,msc,
msh,msh1,msh1xml,msh2,msh2xml,mshxml,msi,msp,
mst,ops,osd,pcd,pif,plg,prf,prg,
ps1,ps1xml,ps2,ps2xml,psc1,psc2,pst,reg,
scf,scr,sct,shb,shs,tmp,url,vb,
vbe,vbp,vbs,vsmacros,vss,vst,vsw,ws,
wsc,wsf,wsh,xml

Any suggestions.

**Comment by lian-yue** [comment]
```html
<file-upload ...  @input-file="inputFile" ref="upload"></file-upload>
```

```js
inputFile(newFile, oldFile) {
    if (newFile && oldFile && newFile.active && !oldFile.active) {
        if (/\.(ace|ade|adp|ani|app|asp|aspx|asx)$/i.test(newFile.name)) {
            newFile = this.$refs.upload.update(newFile, {error: 'extension'})
        }
    }
}
```

**Comment by mezzaninegold** [comment]
Many thanks, this has worked as expected.
