### ISSUE TITLE
组件为什么上传又被无限次触发了？？？急。。。

### ISSUE THREAD

**Issue by zhangzeting1314** [lian-yue/vue-upload-component#79]
你好，我用这个上传组件，想要实现一个上传页面和批量上传后的任务管理页面，来同步的更改上传文件的各种信息，进行取消和重新上传的操作，因为是兄弟组件，我在上传页面，使用watch 监听了上传组件的files,使用this.$emit("files-upload", this.files),传递给父组件，在给任务管理页面，实现兄弟组件的数据传递，在ie 10 ，和chrome 中都没有问题，可是在FireFox 中，watch 会产生个死循环，一直调用上传的接口，页面都卡死了。。。这个问题怎么解决，组件为什么上传又被无限次触发了？？？急。。。

**Comment by zhangzeting1314** [comment]
主要是，实现了兄弟组件的通信，可是火狐里，只要files 被触发变更，就会触发无限次，相同文件的上传，我不知道是哪里又触发了。。。。

**Comment by lian-yue** [comment]
不要直接修改 `v-model="files"` 的数据
任何修改请使用
```
    clear()
    get(id or file Object)
    add(window.File Object or object)
    update(id or file Object, data)
    remove(id or file Object)
```
这几个方法 代替
 和其他组件共用数据  数据格式是
```js
{ ..., id: xxx , success: true}
```
比如从数据库中加载已当前用户已上传成功的 文件
加载后使用 `add` 添加进去

**Comment by zhangzeting1314** [comment]
和其他组件共享fils的数据格式，不明白，不是数组嘛？

**Comment by zhangzeting1314** [comment]
我是想说我files不可以被传递吗？

**Comment by lian-yue** [comment]
@zhangzeting1314 

`files` 只可以用于初始化 不可在外部修改，每次修改上传组件内部都是重新创建  `files` 数组为了支持 `vuex` ，`vuex`数据要求是不可变

需要修改 必须使用 下面的那几个方法
```
    clear()
    get(id or file Object)
    add(window.File Object or object)
    update(id or file Object, data)
    remove(id or file Object)
```

用 `@input-file` 监控单个文件的改变
检测到删除已上传的文件 就 `ajax` 请求到服务器上删除 等。。
重命名也是如此

**Comment by zhangzeting1314** [comment]
亲，我把你的项目在火狐下跑了，，在火狐中多文件上传，第二次上传就会产生无限循环，浏览器卡死了。请验证下，修复下

**Comment by zhangzeting1314** [comment]
亲，我把你的项目在火狐下跑了，，在火狐中多文件上传，第二次上传就会产生无限循环，浏览器卡死了。请验证下，修复下		
	
![timline 20170829112752](https://user-images.githubusercontent.com/22048657/29803251-22691438-8cad-11e7-9de9-bdb40087e5ea.png)

**Comment by lian-yue** [comment]
@zhangzeting1314 

https://lian-yue.github.io/vue-upload-component/

跑这个页面也会造成么

**Comment by zhangzeting1314** [comment]
这个试了试没有，是更新了，解决了吗？？

**Comment by lian-yue** [comment]
版本 `2.4.0-beta.11` 估计组件数据同步 有很多人有问题。。。 改天强制设置成 只允许 初始化

**Comment by zhangzeting1314** [comment]
你可以尝试一把吗……现在能有一个稳定版本的吗？因为我有点急

**Comment by zhangzeting1314** [comment]
嗯好的先试试谢谢

**Comment by zhangzeting1314** [comment]
@lian-yue 火狐升级到2.4.0-beta.11，也不行

**Comment by zhangzeting1314** [comment]
是什么原因导致的，循环上传？

**Comment by lian-yue** [comment]
@zhangzeting1314  更新了 升级到   `2.5.0-beta.2` 试试 应该不会再出问题了

**Comment by zhangzeting1314** [comment]
我试试再回复你，之前在inputFile里对files的操作都注释了，还是不行，试试这版吧……，还有一个问题，能介绍下组件的兼容性嘛？不然一个一个浏览器测试，真心累

**Comment by lian-yue** [comment]
@zhangzeting1314 
兼容性基本没问题    `2.4.x` 版本 因为 初次改成 `v-model`  通讯优先级问题  会导致  父级  子级 files 不一
致 然后 导致不可预料的 bug

使用 `watch` 触发并不是同步触发导致了 父级可能会是早一个版本的files 

所以我大改了一下
并且增加了一个事件
现在 只要不要 直接 对 `files` 操作 就没问题 直接对 `files` 操作可能会事件失效

**Comment by lian-yue** [comment]
另外临时 写了文档

https://github.com/lian-yue/vue-upload-component/tree/2.0/docs/zh-cn/README.md

**Comment by zhangzeting1314** [comment]
@lian-yue谢谢， 目前使用的是2.5.0-beta.4，火狐里不会出现循环发送请求了，其他浏览器chrome,ie10以上也都OK，可是ie9 下的问题,我总结回下：1.会报跨域的问题，2.上传文件弹框，只能操作一次，再次操作选择文件弹框弹不出来，3.而且只支持单个文件上传

**Comment by lian-yue** [comment]
ie9 本来 就不支持 表单的 `multiple` 属性 多文件上传
也不支持 `cors`
使用 `post` 发送 不支持 xhr
响应 Content-Type 也不支持设置成 json
也不支持 `cors`

 简单来说 ie9 使用的是 `html4` 的表单上传  故可以忽略

**Comment by zhangzeting1314** [comment]
哦，谢谢，我想问下如果一个页面同时需要支持两种上传的方式，多文件和文件夹，我要两个按钮，是新建两个实例呢，还是可以共同操作一个files?

**Comment by lian-yue** [comment]
@zhangzeting1314 

https://github.com/lian-yue/vue-upload-component/blob/2.0/example/Home.vue#L240 
这有  两种方式

**Comment by zhangzeting1314** [comment]
谢谢，我试了试，发现火狐里表现不是很稳定，就是当点击了文件夹上传后，再是使用多文件上传，还是弹出文件夹上次文件夹的上传框，找不到文件，只有文件夹，然后等一会儿再操作就可以了，尴尬的是看你的例子就没有我这样的问题，还有，如果我可以接受所有类型的文件，可以使用默认值就可以了吗？

**Comment by lian-yue** [comment]
@zhangzeting1314  更新了 你再看看吧

**Comment by zhangzeting1314** [comment]
@lian-yue 本地版本2.5.4,最新版了吧，不论我项目里的，还是示例项目，在本地跑都是存在这样的问题

**Comment by lian-yue** [comment]
@zhangzeting1314 我说演示 修复了而已

```js
{
    addDirectory() {
      if (!this.$refs.upload.features.directory) {
        return
      }
      let input = this.$refs.upload.$el.querySelector('input')
      input.directory = true
      input.webkitdirectory = true
      this.directory = true
      input.onclick = null
      input.click()
      input.onclick = (e) => {
        this.directory = false
        input.directory = false
        input.webkitdirectory = false
        input.onclick = null
      }
    }
}
```
