### ISSUE TITLE
Error message being fired twice.

### ISSUE THREAD

**Issue by mezzaninegold** [lian-yue/vue-upload-component#81]
Thank you for the help on the restricted files.

I now have an issue, that the error is being fired twice when the file extension fails.

            if (newFile && oldFile && newFile.active && !oldFile.active) {
                if (/\.(ace|ade|adp|ani|app|asp|aspx|asx|bas|bat|cer|chm|cmd|cnt|com|cpl|crt|csh|der|docm|exe|fxp|gadget|hlp|hpj|hta|htc|inf|ins|isp|its|jar|js|jse|ksh|lnk|mad|maf|mag|mam|maq|mar|mas|mat|mau|mav|maw|mda|mdb|mde|mdt|mdw|mdz|mht|mhtml|msc|msh|msh1|msh1xml|msh2|msh2xml|mshxml|msi|msp|mst|ops|osd|pcd|pif|plg|prf|prg|ps1|ps1xml|ps2|ps2xml|psc1|psc2|pst|reg|scf|scr|sct|shb|shs|tmp|url|vb|vbe|vbp|vbs|vsmacros|vss|vst|vsw|ws|wsc|wsf|wsh|xml)$/i.test(newFile.name)) {
                    newFile = this.$refs.upload.update(newFile, {error: 'Invalid file extension'})
                }
            }

                if (newFile.error && !oldFile.error) {
                    // this.error(newFile)
                    Materialize.toast('Error: '+newFile.error+'', 4000)
                    console.log('error', newFile.error, newFile.response)
                }

**Comment by mezzaninegold** [comment]
Should the first line be 
            if (newFile && oldFile) {
instead of 
if (newFile && oldFile && newFile.active && !oldFile.active) {

Could that be the issue?

**Comment by lian-yue** [comment]
```js
let isModifiedError
if (newFile && oldFile && newFile.active && !oldFile.active) {
    if (/\.(ace|ade|adp|ani|app|asp|aspx|asx|bas|bat|cer|chm|cmd|cnt|com|cpl|crt|csh|der|docm|exe|fxp|gadget|hlp|hpj|hta|htc|inf|ins|isp|its|jar|js|jse|ksh|lnk|mad|maf|mag|mam|maq|mar|mas|mat|mau|mav|maw|mda|mdb|mde|mdt|mdw|mdz|mht|mhtml|msc|msh|msh1|msh1xml|msh2|msh2xml|mshxml|msi|msp|mst|ops|osd|pcd|pif|plg|prf|prg|ps1|ps1xml|ps2|ps2xml|psc1|psc2|pst|reg|scf|scr|sct|shb|shs|tmp|url|vb|vbe|vbp|vbs|vsmacros|vss|vst|vsw|ws|wsc|wsf|wsh|xml)$/i.test(newFile.name)) {
        newFile = this.$refs.upload.update(newFile, {error: 'Invalid file extension'})
        isModifiedError = true
    }
}


if (newFile.error && !oldFile.error && !isModifiedError) {
    // this.error(newFile)
    Materialize.toast('Error: '+newFile.error+'', 4000)
    console.log('error', newFile.error, newFile.response)
}


```
