### ISSUE TITLE
Alert to show file is sucessfully uploading / No error

### ISSUE THREAD

**Issue by mezzaninegold** [lian-yue/vue-upload-component#83]
I'm trying to fire a toast message, when the file is successfully uploading. (Upload is in progress)

So no error has been found so the file will be uploaded.

I can send a message if the file has been fully uploaded, but I want to show a message to say for example, a large file is being uploaded.

Any suggestions?

**Comment by lian-yue** [comment]
https://github.com/lian-yue/vue-upload-component/blob/2.0/example/Home.vue#L285

```
inputFile(newFile, oldFile) {
  if (newFile && oldFile && newFile.success && !oldFile.success) {
    // this.success(newFile)
    console.log('success', newFile.response)
    console.log('a large file is being uploaded.')
  }
}
```

**Comment by mezzaninegold** [comment]
Thanks,
This still seems to fire once the file has been uploaded.

I need it to fire before the file has finished.

Could I do something with newFile.progress? At what point is an error in the progress?

Thanks again for all your help and the quick responses. Really appreciated.

**Comment by lian-yue** [comment]
Request response before?
Marked as successful before?

**Comment by mezzaninegold** [comment]
Yes, with that code my response, which goes via postAction to a Laravel route which sends a pusher message. This pusher messages is received by vue before the 'success' message appears.

So I want the message >
Materialize.toast('File uploading!', 4000)
To be sent before the response is successful.

**Comment by lian-yue** [comment]
```html
<file-upload @input-file="inputFile"></file-upload>
```
```js
{
  inputFile(newFile, oldFile) {
    if (newFile && oldFile && newFile.active && newFile.xhr && !newFile.xhr.onreadystatechange) {
      // Need html5 support
      // https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange
      let xhr = newFile.xhr
      xhr.onreadystatechange = function() {
        console.log(xhr.readyState)
      }
    }
  }
}
```

**Comment by lian-yue** [comment]
or 

```html
<file-upload @input-filter="inputFilter"></file-upload>
```

```js
{
  inputFilter(newFile, oldFile, prevent) {
    if (newFile && oldFile && newFile.success && !oldFile.success) {
      // Before writing successful
    }
  }
}
```

**Comment by mezzaninegold** [comment]
The first option worked perfectly. Thanks for looking into this.
