### ISSUE TITLE
第一次上传没事，后面上传都会报错

### ISSUE THREAD

**Issue by licjing** [lian-yue/vue-upload-component#89]
第一次上传没事，后面上传都会报错
Error in event handler for "input-file": "TypeError: Cannot read property 'name' of undefined"
请问这个问题怎么解决？

**Comment by lian-yue** [comment]
你自定义的 `input-file` 事件 有问题 
`newFile` `oldFile` 都可能是 `undefined` 请加判断

**Comment by licjing** [comment]
嗯，发现了。是多次触发input-file事件，是我的判断有问题
