### ISSUE TITLE
extensions这个字段好像不能限制上传文件

### ISSUE THREAD

**Issue by qij1995** [lian-yue/vue-upload-component#95]
我想限制上传excel文件，限制xls，xlsx后缀但是没效果。是不是字段名错了

**Comment by lian-yue** [comment]
`extensions` 不限制选择文件 上传的时候 会自动 自动错误代码  `extension`

https://lian-yue.github.io/vue-upload-component/#/en/examples/full
在右上角 `Options` 自己设置  
![image](https://user-images.githubusercontent.com/6044394/31425583-d7418bd8-ae9a-11e7-97da-83b2eb83a961.png)

然后测试
