### ISSUE TITLE
能支持图片预览之后排序吗？

### ISSUE THREAD

**Issue by user20161119** [lian-yue/vue-upload-component#98]
比如选择多个图片之后，在预览模式下，调整图片的顺序，再上传。

**Comment by lian-yue** [comment]
目前 `add`  方法 还没有插入位置功能 你可以手动修改 `files` 对象 但是 有文件在上传中请不要手动修改 `files` 对象

**Comment by lian-yue** [comment]
后续会考虑添加

**Comment by user20161119** [comment]
谢谢，我的意思是类似这张截图：
![image](https://user-images.githubusercontent.com/123967/31752967-61559f28-b4c0-11e7-8171-36e84edf6cbb.png)
图片预览出来之后，可以拖拽调整图片的顺序，不是靠程序控制。

**Comment by lian-yue** [comment]
添加了 一个 方法 `replace`

`实例 / 方法` 里面

你可以用此方法实现两个文件的移动 替换

https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#实例-方法-replace

请自己手动实现拖拽排序

**Comment by user20161119** [comment]
感谢

发送自 Windows 10 版邮件应用

发件人: LianYue
发送时间: 2017年10月19日 12:56
收件人: lian-yue/vue-upload-component
抄送: jianwen; Author
主题: Re: [lian-yue/vue-upload-component] 能支持图片预览之后排序吗？ (#98)

添加了 一个 方法 replace
实例 / 方法 里面
你可以用此方法实现两个文件的移动 替换
https://lian-yue.github.io/vue-upload-component/#/zh-cn/documents#实例-方法-replace
请自己手动实现拖拽排序
